# Generated by Django 5.0 on 2023-12-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='ReservationModel',
        ),
    ]
