# Generated by Django 5.0 on 2023-12-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_reservation_reservationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='guest_num',
            new_name='guest',
        ),
    ]
