# Generated by Django 5.0 on 2024-01-03 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_basemodel_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.categorymodel'),
        ),
    ]
