# Generated by Django 5.0 on 2024-01-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_basemodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemodel',
            options={'verbose_name': 'base', 'verbose_name_plural': 'Bases'},
        ),
        migrations.AddField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
