# Generated by Django 5.0 on 2023-12-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
