# Generated by Django 5.0.4 on 2024-05-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookmodel',
            constraint=models.UniqueConstraint(fields=('title', 'description'), name='unique_title_description'),
        ),
    ]
