# Generated by Django 5.0.4 on 2024-05-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bookmodel_average_rating_alter_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
